### ISSUE TITLE
Problem: tests that are written are not local, and work in a cascade

### ISSUE THREAD

**Issue by CTAPCKPIM** [holdex/payment-streaming#91]
Example:
- There is a "block" with 4 tests for the function `changeCommissionAddress();`

```JavaScript
// Tests for `changeCommissionAddress();` A
  // Changing the address of the commission
  it('Chainge address fee: address of the admin is changing', async () => {
    await expect(
      this.streamManager.connect(this.admin).changeCommissionAddress(this.payee1.address)
    ).to.emit(this.streamManager, "CommissionAddressChanged")
    .withArgs(this.payee1.address);
  })

  // Expecting revert with `NotAdmin` B
  it('Chainge address fee: only the admin can call the function', async () => {
    await expect(
      this.streamManager.connect(this.payee4).changeCommissionAddress(this.payee1.address)
      ).to.be.revertedWith('NotAdmin')
  })

  // Expecting revert with `InvalidAddress` C
  it('Chainge address fee: not can setting address(0) how address of the admin', async () => {
    await expect(
      this.streamManager.connect(this.payee1).changeCommissionAddress(this.zero)
      ).to.be.revertedWith('InvalidAddress')
  })

  // Expecting revert with `InvalidAddress` D
  it('Chainge address fee: existing address and new address must not match', async () => {
    await expect(
      this.streamManager.connect(this.payee1).changeCommissionAddress(this.payee1.address)
      ).to.be.revertedWith('InvalidAddress')
  })
```

**1)** In test **A**, we set a new address `this.payee1.address`
**2)** In test **D** when we need the same addresses for the `revert`
- beforeEach for tests setting `this.streamManager = await StreamManager.deploy(this.payer.address)`, but for D it is not `this.payer.address` but `this.payee1.address`

In **conclusion**, setting the value in the first test affected the value for the 4th test, this is an example of how `this.` negatively affects the tests, they work, but they are not local to each other

I think we need to **rewrite** the tests without using `this.`
```[tasklist]
### Tasks
- [x] Problem: no 'fixtures'
- [x] Problem: 'createOpenStream();' not rewrited tests
- [x] Problem: 'claim();' not rewrited tests
- [x] Problem: 'terminate();' not rewrited tests
- [x] Problem: 'deposit();' not rewrited tests
- [x] Problem: 'accumulation();' not rewrited tests
- [x] Problem: 'changePayerAddress();' not rewrited tests
- [x] Problem: 'changeCommissionAddress();' not rewrited tests
```

**Comment by georgeciubotaru** [comment]
@zolotokrylin I will also, add that using fixtures will help here.

So, to avoid any issues with `this` will be better to have `const` declarations.

**Comment by zolotokrylin** [comment]
I agree. @CTAPCKPIM go for it

**Comment by zolotokrylin** [comment]
@CTAPCKPIM try not to ping me when you don't need my opinion. Thanks!

**Comment by CTAPCKPIM** [comment]
@zolotokrylin / @markholdex 
As I understand it, wait until they add 100% test coverage, and then continue to rewrite? Because of the code in the functions changes, etc. (#94)

**Comment by zolotokrylin** [comment]
@CTAPCKPIM yes.

**Comment by CTAPCKPIM** [comment]
@georgeciubotaru 
Can this `issues` be closed?

**Comment by georgeciubotaru** [comment]
@CTAPCKPIM No, see my comments from your Previous PR

**Comment by CTAPCKPIM** [comment]
@georgeciubotaru 
I have read and started work
