### ISSUE TITLE
Problem: incorrectly configured tests

### ISSUE THREAD

**Issue by CTAPCKPIM** [holdex/payment-streaming#99]
Correcting the tests:
1) Improved `fixtures`
2) Change the order of tests for each function (`modifier` => `revert`=> `success`)
```[tasklist]
### Tasks
- [ ] https://github.com/holdex/payment-streaming/issues/110
- [ ] https://github.com/holdex/payment-streaming/issues/112
- [ ] https://github.com/holdex/payment-streaming/issues/106
- [ ] https://github.com/holdex/payment-streaming/issues/104
- [ ] https://github.com/holdex/payment-streaming/issues/108
- [ ] https://github.com/holdex/payment-streaming/issues/102
- [ ] https://github.com/holdex/payment-streaming/issues/100
- [ ] https://github.com/holdex/payment-streaming/issues/113
```

**Comment by CTAPCKPIM** [comment]
@georgeciubotaru 
Coverage is 100%
- https://github.com/holdex/payment-streaming/actions/runs/5724036502/job/15509724821
![image](https://github.com/holdex/payment-streaming/assets/83241890/27eb9dff-7823-4507-afc5-f2dd1e11b93d)

(link with last PR + his auto test #114)
